### ISSUE TITLE
Apache Commons Missing

### ISSUE THREAD

**Issue by mirosval** [arktekk/sbt-aether-deploy#45] opened 2017-05-09 13:21 UTC
During `publish` I get:

```
00:00:32.594 java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
00:00:32.595 	at org.apache.maven.repository.internal.DefaultVersionResolver.setMetadataResolver(DefaultVersionResolver.java:140)
00:00:32.596 	at org.apache.maven.repository.internal.DefaultVersionResolver.initService(DefaultVersionResolver.java:121)
00:00:32.598 	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance(DefaultServiceLocator.java:171)
00:00:32.599 	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances(DefaultServiceLocator.java:141)
00:00:32.600 	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance(DefaultServiceLocator.java:127)
00:00:32.601 	at org.eclipse.aether.impl.DefaultServiceLocator.getService(DefaultServiceLocator.java:291)
00:00:32.602 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.initService(DefaultRepositorySystem.java:139)
00:00:32.603 	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance(DefaultServiceLocator.java:171)
00:00:32.605 	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances(DefaultServiceLocator.java:141)
00:00:32.606 	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance(DefaultServiceLocator.java:127)
00:00:32.607 	at org.eclipse.aether.impl.DefaultServiceLocator.getService(DefaultServiceLocator.java:291)
00:00:32.608 	at aether.internal.Booter$.newRepositorySystem(Booter.scala:48)
00:00:32.609 	at aether.internal.Booter$.apply(Booter.scala:54)
00:00:32.610 	at aether.AetherPlugin$class.deployIt(Plugin.scala:123)
00:00:32.610 	at aether.AetherPlugin$.deployIt(Plugin.scala:27)
00:00:32.611 	at aether.AetherPlugin$$anonfun$deployTask$1.apply(Plugin.scala:74)
00:00:32.612 	at aether.AetherPlugin$$anonfun$deployTask$1.apply(Plugin.scala:72)
00:00:32.613 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
00:00:32.614 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
00:00:32.614 	at sbt.std.Transform$$anon$4.work(System.scala:63)
00:00:32.615 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
00:00:32.616 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
00:00:32.617 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
00:00:32.617 	at sbt.Execute.work(Execute.scala:237)
00:00:32.618 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
00:00:32.619 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
00:00:32.619 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
00:00:32.620 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
00:00:32.621 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:00:32.622 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
00:00:32.622 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:00:32.623 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
00:00:32.624 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
00:00:32.625 	at java.lang.Thread.run(Thread.java:745)
```

I solved it for now by adding the following to `project/plugins.sbt`:
```
libraryDependencies ++= Seq(
  "org.apache.commons" % "commons-lang3" % "3.5"
)
```

**Comment by hamnis** [comment] 2017-05-09 13:24
Transitive dependencies... gotta love 'em. Will fix.

**Comment by hamnis** [comment] 2017-05-09 13:25
Duplicate of #44

**Closed by hamnis** 2017-05-09 13:25 UTC
